FROM registry:2.0
MAINTAINER Hideyuki Takei <takehide22@gmail.com>

ADD ./config.yml /docker-registry/config/config.yml
env DOCKER_REGISTRY_CONFIG /docker-registry/config/config.yml

env SETTINGS_FLAVOR prod

